# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1010, 696)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(60, 160, 861, 501))
        self.stackedWidget.setStyleSheet("color:rgb(180, 255, 127);\n"
"background-color:rgb(0, 255, 160); ")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_0 = QtWidgets.QWidget()
        self.page_0.setObjectName("page_0")
        self.label_7 = QtWidgets.QLabel(self.page_0)
        self.label_7.setGeometry(QtCore.QRect(70, 90, 261, 291))
        self.label_7.setStyleSheet("color:rgb(0, 0, 0);\n"
"background-color:rgb(255, 255, 255); ")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.pushButton_10 = QtWidgets.QPushButton(self.page_0)
        self.pushButton_10.setGeometry(QtCore.QRect(460, 160, 75, 23))
        self.pushButton_10.setStyleSheet("color:rgb(0, 0, 0);\n"
"background-color:rgb(255, 255, 255); ")
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.page_0)
        self.pushButton_11.setGeometry(QtCore.QRect(460, 210, 75, 23))
        self.pushButton_11.setStyleSheet("color:rgb(0, 0, 0);\n"
"background-color:rgb(255, 255, 255); ")
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(self.page_0)
        self.pushButton_12.setGeometry(QtCore.QRect(460, 100, 75, 23))
        self.pushButton_12.setStyleSheet("color:rgb(0, 0, 0);\n"
"background-color:rgb(255, 255, 255); ")
        self.pushButton_12.setObjectName("pushButton_12")
        self.label_8 = QtWidgets.QLabel(self.page_0)
        self.label_8.setGeometry(QtCore.QRect(90, 410, 81, 31))
        self.label_8.setStyleSheet("color:rgb(0, 0, 0);\n"
"background-color:rgb(255, 255, 255); ")
        self.label_8.setObjectName("label_8")
        self.textEdit_4 = QtWidgets.QLabel(self.page_0)
        self.textEdit_4.setGeometry(QtCore.QRect(190, 410, 104, 31))
        self.textEdit_4.setStyleSheet("color:rgb(0, 0, 0);\n"
"background-color:rgb(255, 255, 255); ")
        self.textEdit_4.setObjectName("textEdit_4")
        self.stackedWidget.addWidget(self.page_0)
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.graphicsView = QtWidgets.QGraphicsView(self.page_1)
        self.graphicsView.setGeometry(QtCore.QRect(70, 80, 231, 211))
        self.graphicsView.setStyleSheet("color:rgb(0, 0, 0);\n"
"background-color:rgb(255, 255, 255); ")
        self.graphicsView.setObjectName("graphicsView")
        self.pushButton = QtWidgets.QPushButton(self.page_1)
        self.pushButton.setGeometry(QtCore.QRect(700, 80, 75, 23))
        self.pushButton.setStyleSheet("color: rgb(0,0,0);\n"
"background-color: rgb(255,255,255)")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.page_1)
        self.pushButton_2.setGeometry(QtCore.QRect(700, 130, 75, 23))
        self.pushButton_2.setStyleSheet("color: rgb(0,0,0);\n"
"background-color: rgb(255,255,255)")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.page_1)
        self.pushButton_3.setGeometry(QtCore.QRect(700, 230, 75, 23))
        self.pushButton_3.setStyleSheet("color: rgb(0,0,0);\n"
"background-color: rgb(255,255,255)")
        self.pushButton_3.setObjectName("pushButton_3")
        self.label = QtWidgets.QLabel(self.page_1)
        self.label.setGeometry(QtCore.QRect(70, 335, 81, 21))
        self.label.setStyleSheet("color: rgb(0,0,0);\n"
"background-color: rgb(255,255,255)")
        self.label.setObjectName("label")
        self.textEdit = QtWidgets.QTextEdit(self.page_1)
        self.textEdit.setGeometry(QtCore.QRect(160, 330, 151, 31))
        self.textEdit.setStyleSheet("color: rgb(0,0,0);\n"
"background-color: rgb(255,255,255)")
        self.textEdit.setObjectName("textEdit")
        self.pushButton_4 = QtWidgets.QPushButton(self.page_1)
        self.pushButton_4.setGeometry(QtCore.QRect(70, 390, 75, 23))
        self.pushButton_4.setStyleSheet("color: rgb(0,0,0);\n"
"background-color: rgb(255,255,255)")
        self.pushButton_4.setObjectName("pushButton_4")
        self.tableWidget = QtWidgets.QTableWidget(self.page_1)
        self.tableWidget.setEnabled(True)
        self.tableWidget.setGeometry(QtCore.QRect(350, 80, 256, 361))
        self.tableWidget.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0)")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setRowCount(0)
        self.pushButton_8 = QtWidgets.QPushButton(self.page_1)
        self.pushButton_8.setGeometry(QtCore.QRect(700, 180, 75, 23))
        self.pushButton_8.setStyleSheet("color: rgb(0,0,0);\n"
"background-color: rgb(255,255,255)")
        self.pushButton_8.setObjectName("pushButton_8")
        self.stackedWidget.addWidget(self.page_1)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.frame = QtWidgets.QFrame(self.page_2)
        self.frame.setGeometry(QtCore.QRect(50, 220, 311, 201))
        self.frame.setStyleSheet("background-color:rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(40, 50, 61, 41))
        self.label_2.setStyleSheet("color:rgb(0, 0, 0);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(110, 10, 101, 41))
        self.label_3.setStyleSheet("color:rgb(0, 0, 0);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(40, 120, 61, 41))
        self.label_4.setStyleSheet("color:rgb(0, 0, 0);")
        self.label_4.setObjectName("label_4")
        self.textEdit_2 = QtWidgets.QTextEdit(self.frame)
        self.textEdit_2.setGeometry(QtCore.QRect(120, 60, 104, 31))
        self.textEdit_2.setObjectName("textEdit_2")
        self.textEdit_3 = QtWidgets.QTextEdit(self.frame)
        self.textEdit_3.setGeometry(QtCore.QRect(120, 120, 104, 31))
        self.textEdit_3.setObjectName("textEdit_3")
        self.textEdit_3.setStyleSheet("color:rgb(0, 0, 0);\n"
                                        "background-color:rgb(255, 255, 255); \n"
                                        "")

        self.pushButton_9 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_9.setGeometry(QtCore.QRect(50, 450, 75, 23))
        self.pushButton_9.setStyleSheet("color:rgb(0, 0, 0);\n"
"background-color:rgb(255, 255, 255); \n"
"")
        self.pushButton_9.setObjectName("pushButton_9")
        self.label_5 = QtWidgets.QLabel(self.page_2)
        self.label_5.setGeometry(QtCore.QRect(420, 150, 311, 271))
        self.label_5.setStyleSheet("color:rgb(0, 0, 0);\n"
"background-color:rgb(255, 255, 255); ")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.page_2)
        self.label_6.setGeometry(QtCore.QRect(560, 100, 101, 41))
        self.label_6.setStyleSheet("color:rgb(0, 0, 0);")
        self.label_6.setObjectName("label_6")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.page_2)
        self.tableWidget_2.setGeometry(QtCore.QRect(70, 60, 256, 121))
        self.tableWidget_2.setStyleSheet("\n"
"color:rgb(0, 0, 0);\n"
"background-color:rgb(255, 255, 255); \n"
"")
        self.tableWidget_2.setRowCount(0)
        self.tableWidget_2.setColumnCount(2)
        self.tableWidget_2.setEnabled(True)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.label_9 = QtWidgets.QLabel(self.page_2)
        self.label_9.setGeometry(QtCore.QRect(160, 10, 61, 41))
        self.label_9.setStyleSheet("color:rgb(0, 0, 0);")
        self.label_9.setObjectName("label_9")
        self.pushButton_13 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_13.setGeometry(QtCore.QRect(270, 20, 75, 23))
        self.pushButton_13.setStyleSheet("color:rgb(0, 0, 0);\n"
"background-color:rgb(255, 255, 255); \n"
"")
        self.pushButton_13.setObjectName("pushButton_13")
        self.stackedWidget.addWidget(self.page_2)
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(80, 20, 101, 41))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(220, 20, 101, 41))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(350, 20, 101, 41))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_5.raise_()
        self.pushButton_6.raise_()
        self.pushButton_7.raise_()
        self.stackedWidget.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        self.category_dict = {}
        self.new_model_config_file = ""
        self.pushButton.clicked.connect(self.load)
        self.pushButton_2.clicked.connect(self.save)
        self.pushButton_3.clicked.connect(self.clear)
        self.pushButton_4.clicked.connect(self.imageclass)
        self.pushButton_5.clicked.connect(self.d1)
        self.pushButton_6.clicked.connect(self.d2)
        self.pushButton_7.clicked.connect(self.d0)
        self.pushButton_8.clicked.connect(self.info)
        self.pushButton_9.clicked.connect(self.train)
        self.tableWidget.itemClicked.connect(self.show_image)
        self.pushButton_13.clicked.connect(self.load_data)
        self.pushButton_10.clicked.connect(self.cameraStart)
        self.pushButton_11.clicked.connect(self.cameraStop)
        self.pushButton_12.clicked.connect(self.loadModel)
        # self.pushButton.clicked.connect(MainWindow.load)
        # self.pushButton_2.clicked.connect(MainWindow.save)
        # self.pushButton_3.clicked.connect(MainWindow.clear)
        # self.pushButton_4.clicked.connect(MainWindow.imageclass)
        # self.pushButton_9.clicked.connect(MainWindow.train)
        # self.pushButton_5.clicked.connect(MainWindow.display)
        # self.pushButton_6.clicked.connect(MainWindow.display)
        # self.pushButton_7.clicked.connect(MainWindow.display)
        # self.pushButton_10.clicked.connect(MainWindow.cameraStart)
        # self.pushButton_11.clicked.connect(MainWindow.cameraStop)
        # self.pushButton_8.clicked.connect(MainWindow.info)
        # self.pushButton_13.clicked.connect(MainWindow.load_data)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_10.setText(_translate("MainWindow", "开启摄像头"))
        self.pushButton_11.setText(_translate("MainWindow", "停止"))
        self.pushButton_12.setText(_translate("MainWindow", "模型导入"))
        self.label_8.setText(_translate("MainWindow", "预测类别"))
        self.pushButton.setText(_translate("MainWindow", "导入"))
        self.pushButton_2.setText(_translate("MainWindow", "保存"))
        self.pushButton_3.setText(_translate("MainWindow", "清理"))
        self.label.setText(_translate("MainWindow", "请输入类别："))
        self.pushButton_4.setText(_translate("MainWindow", "确认"))
        self.pushButton_8.setText(_translate("MainWindow", "类别信息统计"))
        self.label_2.setText(_translate("MainWindow", "模型大小"))
        self.label_3.setText(_translate("MainWindow", "模型重要参数"))
        self.label_4.setText(_translate("MainWindow", "训练集比例"))
        self.pushButton_9.setText(_translate("MainWindow", "开始训练"))
        self.label_6.setText(_translate("MainWindow", "结果展示"))
        self.label_9.setText(_translate("MainWindow", "数据信息"))
        self.pushButton_13.setText(_translate("MainWindow", "数据导入"))
        self.pushButton_5.setText(_translate("MainWindow", "数据处理"))
        self.pushButton_6.setText(_translate("MainWindow", "模型训练"))
        self.pushButton_7.setText(_translate("MainWindow", "在线预测"))


    def d0(self):
        self.stackedWidget.setCurrentIndex(0)

    def d1(self):
        self.stackedWidget.setCurrentIndex(1)

    def d2(self):
        self.stackedWidget.setCurrentIndex(2)